spring.application.name=user-service-test

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=false

spring.flyway.enabled=true

spring.kafka.bootstrap-servers=localhost:9092

logging.level.org.springframework=WARN